FROM docker.io/library/mysql:8.0

MAINTAINER "CHOI GOOKHYUN <tang@dustbox.kr>"

# 환경 변수로 기본 계정/비번 설정
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=takku_db
ENV MYSQL_USER=takku
ENV MYSQL_PASSWORD=takku1234

# UTF-8 설정을 위한 커스텀 my.cnf 복사
COPY docker/my.cnf /etc/mysql/conf.d/my.cnf

# 초기화 SQL 추가 (컨테이너 최초 실행 시 실행됨)
ADD docker/takku_mysql.sql /docker-entrypoint-initdb.d/

